<?php

$routeRegister = $this->dx()->getModuleOptions('dxuser')->getRouteRegistration();
$routePasswordReset = $this->dx()->getModuleOptions('dxuser')->getRoutePasswordReset();
if(isset($this->error))
{
	$this->dxAlert()->addError('<b>Login Error</b><br />Email address and Password don\'t match.');
}
$html = '';
$this->dxBreadcrumb()->add('memberLogin', array('anchor' => 'Member Login'));
$this->dxHtml()->setTitle('Member Login');
$form = $this->form;
$form->prepare();
$html .= $this->formTwb($form, $this->dx()->getModuleOptions()->getFormTypeLayout(), $this->formDisplayOptions);
$html .= '<a href="' . $this->url($routePasswordReset) . ($this->redirect ? '?redirect=' . $this->redirect : '') . '">Forgot Password?</a>';
if ($this->enableRegistration) :
	$html .= ' | Not registered? <a href="' . $this->url($routeRegister) . ($this->redirect ? '?redirect=' . $this->redirect : '') . '">Sign up!</a>';
endif;
$socialButtons = '';
//foreach ($this->scnSocialAuthOptions->getEnabledProviders() as $provider) {
//    $socialButtons .= $this->dxHtml()->socialSignInButton($provider);
//}
if(!empty($socialButtons))
{
	$socialButtons .= '<h2>Social Login</h2>';
	$this->dxSidebar()->appendToRight('socialButtons', $socialButtons);
}


echo $html;