<?php

$routeRegister = $this->dxConfig()->getOptions('dxuser')->getRouteRegistration();
$routePasswordReset = $this->dxConfig()->getOptions('dxuser')->getRoutePasswordReset();
$html = '';
$this->dxBreadcrumb()->add('memberLogin', array('anchor' => 'Member Login'));
$this->dxHtml()->setTitle('Member Login');
$form = $this->form;
$form->prepare();
$html .= $this->formTwb($form, $this->dxConfig()->getOptions()->getFormTypeLayout(), $this->formDisplayOptions);
if ($this->enableRegistration) :
	$html .= 'Not registered? <a href="' . $this->url($routeRegister) . ($this->redirect ? '?redirect=' . $this->redirect : '') . '">Sign up!</a>';
endif;

$html .= '<br /><a href="' . $this->url($routePasswordReset) . ($this->redirect ? '?redirect=' . $this->redirect : '') . '">Forgot Password?</a>';

echo $html;