<h1>Sign In</h1>

<?php
$routeRegister = $this->dxConfig()->getOptions('dxuser')->getRouteRegistration();
$routePasswordReset = $this->dxConfig()->getOptions('dxuser')->getRoutePasswordReset();
$form = $this->loginForm;
$form->prepare();
$form->setAttribute('action', $this->url('dx-user-login'));
$form->setAttribute('method', 'post');
?>

<?php echo $this->form()->openTag($form) ?>

    <dl class="zend_form">
        <?php echo $this->formElementErrors($form->get('identity')) ?>

        <dt><?php echo $this->formLabel($form->get('identity')) ?></dt>
        <dd><?php echo $this->formInput($form->get('identity')) ?></dd>

        <dt><?php echo $this->formLabel($form->get('credential')) ?></dt>
        <dd><?php echo $this->formInput($form->get('credential')) ?></dd>

        <?php if ($this->redirect): ?>
            <input type="hidden" name="redirect" value="<?php echo $this->redirect ?>" />
        <?php endif ?>

        <dd><?php echo $this->formButton($form->get('submit')) ?></dd>
    </dl>

<?php echo $this->form()->closeTag() ?>

<?php if ($this->enableRegistration) : ?>
Not registered? <a href="<?php echo $this->url($routeRegister) . ($this->redirect ? '?redirect='.$this->redirect : '') ?>">Sign up!</a>
<?php endif; ?>
<br />
<a href="<?php echo $this->url($routePasswordReset) . ($this->redirect ? '?redirect='.$this->redirect : '') ?>">Forgot Password?</a>