<?php

$html = '';
$this->dxBreadcrumb()->add('memberRegistration', array('anchor' => 'Member Registration'));
if ($this->enableRegistration)
{
	$this->dxHtml()->setTitle('Member Registration');
	$form = $this->form;
	$form->prepare();
	$html .= $this->formTwb($form, $this->dxConfig()->getOptions()->getFormTypeLayout(), $this->formDisplayOptions);
}
else
{
	$this->dxAlert()->addError('Registration is disabled.');
}

echo $html;