<?php

$avatar = '';
//$avatar .= '<h3>Hello, ' . $this->zfcUserDisplayName() . '!</h3>';
$avatar .= '<a target="_blank" href="http://gravatar.com" title="Change your avatar at Gravatar.com">' . $this->gravatar($this->zfcUserIdentity()->getEmail())->setImgSize(150) . '</a>';
//$avatar .= '<br />Change your avatar<br />at gravatar.com';
$this->dxSidebar()->appendToLeft('avatar', $avatar);

$html = '';

$html .= '<h3>Hello, ' . $this->zfcUserDisplayName() . '!</h3>';
$html .= 'Content';

echo $html;
