<?php

$html = '';
$this->dxBreadcrumb()->add('memberAccount', array('anchor' => 'Account'));
$this->dxBreadcrumb()->add('memberAccountEmail', array('anchor' => 'Email Address'));
$this->partial('dx-user/account/nav');

$this->dxHtml()->setTitle('Account Email Address');
$displayForm = TRUE;
if ($this->success)
{
//	$this->dxAlert()->addSuccess('<strong>Successfull</strong><br />Email address updated.');
	if ($this->enableEmailVerification)
	{
		$verifyString = '';
		if ($this->dx()->getModuleOptions()->inDevelopment())
		{
			$verifyUrl = $this->dxHtml()->url('dx-user-email-verify', 
							array('email' => urlencode($this->userCode->getUser()->getEmail()), 
									'code' => $this->userCode->getCode()), 
							array('useSecureUrl' => TRUE, 'useAbsoluteUrl' => TRUE));
			$verifyString .= '<a id="urlRegisterVerify" href="' . $verifyUrl . '" title="Verify Now">' . $verifyUrl . '</a><br /><br />';
		}
		$html .= '<div class="alert alert-block alert-success">
				<button type="button" class="close" data-dismiss="alert">×</button>
				<h4>Email verification sent!</h4>
				<br />
				We sent an email containing instruction on how to verify your new email address.
				<br />
				Kindly check your bulk or spam box for emails from us.
				<br />
				<br />
				' . $verifyString . '
				Thank you very much.
			</div>';
		$displayForm = FALSE;
	}
}
else
{
	if ($this->passwordError)
	{
		$this->dxAlert()->addError('<strong>Password error</strong><br />Account password don\'t match.');
	}
}
if (isset($this->emailVerified) && !$this->emailVerified)
{
		$html .= '<div class="alert alert-block">
				<button type="button" class="close" data-dismiss="alert">×</button>
				<h4>Need attention!</h4>
				<br />
				You still have to verify your email address (' . $this->emailAddress . ').
				<br />
				Kindly check your bulk or spam box for emails from us.
				<br />
				<br />
				If you can\'t find the verification code click below to Resend the Email Verification code
				<br />
				<br />
				Thank you very much.
			</div>';
		$html .= '<a href="' . $this->dxHtml()->url('dx-user-account/resend-email-verification') . '" 
					class="btn btn-large btn-primary">
					<i class="icon-white icon-arrow-right"></i> Resend email verification code</a>';
		$displayForm = FALSE;
}

if($displayForm)
{
	$form = $this->form;
	$form->prepare();
	$html .= $this->formTwb($form, $this->dx()->getModuleOptions()->getFormTypeLayout(), $this->formDisplayOptions);	
}

echo $html;
