<?php

$html = '';
$this->dxBreadcrumb()->add('memberAccount', array('anchor' => 'Member Account'));
$this->partial('dx-user/account/nav');

$this->dxHtml()->setTitle('Update Password');

if ($this->success)
{
	$this->dxAlert()->addSuccess('<strong>Successfull</strong><br />Password updated.');
}
else
{
	if ($this->oldPasswordError)
	{
		$this->dxAlert()->addError('<strong>Password error</strong><br />Account password don\'t match.');
	}
}

$form = $this->form;
$form->prepare();
$html .= $this->formTwb($form, $this->dxConfig()->getOptions()->getFormTypeLayout(), $this->formDisplayOptions);

echo $html;
