<?php

$html = '';
$this->dxBreadcrumb()->add('passwordReset', array('anchor' => 'Reset Password'));
$html .= '<h1>Reset Password</h1>';

if ($this->success)
{
	$html .= '<div class="alert alert-block alert-success">
				<button type="button" class="close" data-dismiss="alert">×</button>
				<h4>Email sent!</h4>
				<br />
				We sent an email containing instruction on how to reset your password.
				<br />
				Kindly check your bulk or spam box for emails from us.
				<br />
				<br />
				Thank you very much.
			</div>';
	$html .= '<a href="' . $this->url($this->dxModuleOptions()->getOptions('dxuser')->getRouteMain()) . '" 
		class="btn btn-large btn-primary">
		<i class="icon-white icon-arrow-right"></i> Click here to continue...</a>';
}
else
{
	$form = $this->form;
	$form->prepare();
	$html .= $this->formTwb($form, $this->formType, $this->formDisplayOptions);
}
echo $html;