<?php

$html = '';
$this->dxBreadcrumb()->add('passwordReset', array('anchor' => 'Reset Password'));
$this->dxHtml()->setTitle('Reset Password');
if ($this->success)
{
	$html .= '<div class="alert alert-block alert-success">
				<button type="button" class="close" data-dismiss="alert">×</button>
				<h4>Password successfully changed!</h4>
				<br />
				Your password is now updated. 
				<br />We sent an email to your account email address of the changes in your account.
				<br />
				<br />
				Thank you very much.
			</div>';
	$html .= '<a href="' . $this->url('dx-user-login') . '" 
		class="btn btn-large btn-primary">
		<i class="icon-white icon-arrow-right"></i> Click here to login...</a>';
}
else
{
	$form = $this->form;
	$form->prepare();
	$html .= $this->formTwb($form, $this->dxConfig()->getOptions()->getFormTypeLayout(), $this->formDisplayOptions);
}
echo $html;